services:
  - type: web
    name: sdt-calculator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --worker-class gevent --timeout 300 --keep-alive 5
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
